GET http://localhost:3000/customers/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDQxNTY0MzYsImV4cCI6MTYwNDE1NjczNn0.BvfSf1t5umVDBtlp9nFi_TPD97rVIeI9UkL-yReTEaU
###

POST http://localhost:3000/login/
Content-Type:application/json

{
    "username":"admin"
}



###

POST http://localhost:3000/token/
Content-Type:application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDQxNTY0MzZ9.GJqe7C0PuFhs89HmkdViKzmYDjGAglb6GaEFUu7AzIE"
}

###

DELETE http://localhost:3000/logout/
Content-Type:application/json

{
    "token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiYWRtaW4iLCJpYXQiOjE2MDQxNTY0MzZ9.GJqe7C0PuFhs89HmkdViKzmYDjGAglb6GaEFUu7AzIE"
}